version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mtgtracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mtgtracker:
    image: ghcr.io/kiwiidb/kiwiidb/mtgtracker:latest
    container_name: mtgtracker
    environment:
      POSTGRES_DSN: "host=postgres user=postgres password=postgres dbname=mtgtracker port=5432 sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
