name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate tag
        id: generate-tag
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          SHORT_SHA=${GITHUB_SHA:0:7}
          TAG="${BRANCH_NAME}-${SHORT_SHA}"
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "FILTERED_TAGS=${TAG}" >> $GITHUB_ENV
          echo "IMAGENAME=mtgtracker" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: build
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: mtgtracker
          tags: ${{ steps.generate-tag.outputs.tag }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout deployment repo
        uses: actions/checkout@v2
        with:
          repository: kiwiidb/mtgtracker-deployment
          path: infrastructure
          token: ${{ secrets.GITHUB_TOKEN }}
      # staging environment is tracking main
      - name: Update staging environment
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: fjogeleit/yaml-update-action@v0.16.1
        with:
          valueFile: 'staging/values.yaml'
          propertyPath: '${{ env.IMAGENAME }}.image.tag'
          value: ${{ env.FILTERED_TAGS }}
          repository: kiwiidb/mtgtracker-deployment
          branch: main
          createPR: false
          message: 'CD: deploy staging ${{ env.IMAGENAME }} version ${{ env.FILTERED_TAGS }}'
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workDir: infrastructure